version: '3.7'

services:
  users-service:
    container_name: users-service
    build: 
      context: ./users-service
    volumes: 
    - ./users-service:/app
    - /app/node_modules
    expose:
    - 3001
    networks: 
    - gateway-net
    tty: true
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    volumes: 
    - ./api-gateway:/app
    - /app/node_modules
    ports:
     - 3000:3000
    networks: 
    - gateway-net
    tty: true

networks: 
  gateway-net:
    name: gateway-net
    driver: bridge